// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLa-OrGmqAxP37so90r_TzrSuwZmYjRFc',
    appId: '1:391864326169:web:6c8a18eb841bc7120f3288',
    messagingSenderId: '391864326169',
    projectId: 'newfirebase-e7b76',
    authDomain: 'newfirebase-e7b76.firebaseapp.com',
    storageBucket: 'newfirebase-e7b76.appspot.com',
    measurementId: 'G-8F3X0TTSTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX26d3U5zzbB-Bl85NP02dO5tFqh46qfA',
    appId: '1:391864326169:android:60f3ef8c29976c620f3288',
    messagingSenderId: '391864326169',
    projectId: 'newfirebase-e7b76',
    storageBucket: 'newfirebase-e7b76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc5RaaPJtWFqZeAkGdHvZd1DQyfjQ00n4',
    appId: '1:391864326169:ios:e307efcce7ed08400f3288',
    messagingSenderId: '391864326169',
    projectId: 'newfirebase-e7b76',
    storageBucket: 'newfirebase-e7b76.appspot.com',
    iosClientId: '391864326169-894t08hlheqia2tq1ill3ligjgaprtk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebasenew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc5RaaPJtWFqZeAkGdHvZd1DQyfjQ00n4',
    appId: '1:391864326169:ios:e307efcce7ed08400f3288',
    messagingSenderId: '391864326169',
    projectId: 'newfirebase-e7b76',
    storageBucket: 'newfirebase-e7b76.appspot.com',
    iosClientId: '391864326169-894t08hlheqia2tq1ill3ligjgaprtk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebasenew',
  );
}
